"""add pages table

Revision ID: 21ebdfcbfac5
Revises:
Create Date: 2025-12-29 16:50:52.697671

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "21ebdfcbfac5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
